#!/bin/bash
# 
# Nome: proxyManager
# Autor: Willian Martins - willian.martins@msn.com
# Descricao: Gerencia configuracao de Proxy do Gnome.
# 

enableProxy () 
{
	clear ; echo
				gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '192.168.8.0/24', '10.0.0.0/8', '172.16.0.0/12', '.samedomain.example']"
        gsettings set org.gnome.system.proxy mode "manual"
        gsettings set org.gnome.system.proxy use-same-proxy "true"
				gsettings set org.gnome.system.proxy.http authentication-password "Your password here. Blank for none."
        gsettings set org.gnome.system.proxy.http authentication-user "Your proxy username here. Blank for none."
        gsettings set org.gnome.system.proxy.http enabled "true"
        gsettings set org.gnome.system.proxy.http host "squid-proxy.samedomain.example"
        gsettings set org.gnome.system.proxy.http port "3128"
        gsettings set org.gnome.system.proxy.http use-authentication "false"
        gsettings set org.gnome.system.proxy.https host "squid-proxy.samedomain.example"
        gsettings set org.gnome.system.proxy.https port "3128"
        gsettings set org.gnome.system.proxy.ftp host "squid-proxy.samedomain.example"
        gsettings set org.gnome.system.proxy.ftp port "3128"
}

disableProxy ()
{
	clear ; echo
        gsettings set org.gnome.system.proxy ignore-hosts "[]"
        gsettings set org.gnome.system.proxy mode "none"
        gsettings set org.gnome.system.proxy use-same-proxy "false"
        gsettings set org.gnome.system.proxy.http authentication-password " "
        gsettings set org.gnome.system.proxy.http authentication-user " "
        gsettings set org.gnome.system.proxy.http enabled "false"
        gsettings set org.gnome.system.proxy.http host " "
        gsettings set org.gnome.system.proxy.http port "0"
        gsettings set org.gnome.system.proxy.http use-authentication "false"
        gsettings set org.gnome.system.proxy.https host " "
        gsettings set org.gnome.system.proxy.https port "0"
        gsettings set org.gnome.system.proxy.ftp host " "
        gsettings set org.gnome.system.proxy.ftp port "0"
}

case $1 in
	start)	enableProxy ; echo "Proxy Habilitado no Gnome" ; echo ;;
	stop)	disableProxy ; echo "Proxy Desabilitado no Gnome" ; echo ;;
	*)	clear ; echo ; echo "Erro de sintaxe. Utilize start|stop" ; echo ;;
esac

