#!/bin/bash
# 
# Nome: proxyManager
# Autor: Willian Martins - willian.martins@msn.com
# Descricao: Gerencia configuracao de Proxy do Gnome.
# 

enableProxy () 
{
	clear ; echo
	gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '192.168.0.0/16', '10.0.0.0/8', '172.16.0.0/12', '.netmaster.intra', 'webmailsp.gruposbf.com.br']"
        gsettings set org.gnome.system.proxy mode "manual"
        gsettings set org.gnome.system.proxy use-same-proxy "true"
	gsettings set org.gnome.system.proxy.http authentication-password " "
        gsettings set org.gnome.system.proxy.http authentication-user " "
        gsettings set org.gnome.system.proxy.http enabled "true"
        gsettings set org.gnome.system.proxy.http host "127.0.0.1"
        gsettings set org.gnome.system.proxy.http port "8181"
        gsettings set org.gnome.system.proxy.http use-authentication "false"
        gsettings set org.gnome.system.proxy.https host "127.0.0.1"
        gsettings set org.gnome.system.proxy.https port "8181"
        gsettings set org.gnome.system.proxy.ftp host "127.0.0.1"
        gsettings set org.gnome.system.proxy.ftp port "8181"
}

disableProxy ()
{
	clear ; echo
        gsettings set org.gnome.system.proxy ignore-hosts "[]"
        gsettings set org.gnome.system.proxy mode "none"
        gsettings set org.gnome.system.proxy use-same-proxy "false"
        gsettings set org.gnome.system.proxy.http authentication-password " "
        gsettings set org.gnome.system.proxy.http authentication-user " "
        gsettings set org.gnome.system.proxy.http enabled "false"
        gsettings set org.gnome.system.proxy.http host " "
        gsettings set org.gnome.system.proxy.http port "0"
        gsettings set org.gnome.system.proxy.http use-authentication "false"
        gsettings set org.gnome.system.proxy.https host " "
        gsettings set org.gnome.system.proxy.https port "0"
        gsettings set org.gnome.system.proxy.ftp host " "
        gsettings set org.gnome.system.proxy.ftp port "0"
}

case $1 in
	start)	enableProxy ; echo "Proxy Habilitado no Gnome" ; echo ;;
	stop)	disableProxy ; echo "Proxy Desabilitado no Gnome" ; echo ;;
	*)	clear ; echo ; echo "Erro de sintaxe. Utilize start|stop" ; echo ;;
esac
